### ISSUE TITLE
mapのpack/unpack

### ISSUE THREAD

**Issue by phi16** [phi16/JJ3S#1]
`map[x+y*31] = m` という場合があるのでpack/unpackするとしたらlua側のサポートが必須
mapを1/2に(8bit/8bitで16bit)packすれば結構余裕ができそうという話

unpackにCIR8回 + 0x00ffでANDが必要なのでめんどくさそう (まぁそれでもメモリは減る)

**Comment by kaz** [comment]
implemented https://github.com/kaz/jj3s-lua/commit/e649777a7a0de0330e4a5c309364e87ee648d5bd

**Comment by phi16** [comment]
:pro:
